### ISSUE TITLE
Interpreter switching logic assumes only lowercase .z for data files

### ISSUE THREAD

**Issue by BroadcastGames** [sussman/twisty#80]
main.c line 43: https://github.com/sussman/twisty/blob/master/app/src/main/jni/glkmain/main.c#L43

There are downloads with uppercase filenames on the major hosting sites.  Thank you.

**Comment by rgeens** [comment]
Fixed in https://github.com/sussman/twisty/commit/b3b955ba716dec0deca15475efd83ea926e094d9

**Comment by BroadcastGames** [comment]
Thank you
